# Generated by Django 5.2.2 on 2025-06-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Посещаемость', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='school_app.student', verbose_name='Дети'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='additional_groups',
            field=models.ManyToManyField(blank=True, related_name='additional_teachers', to='school_app.group', verbose_name='Дополнительные группы'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='school_app.subject', verbose_name='Предметы'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lesson', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'date', 'group')},
        ),
    ]
