# Generated by Django 5.2.2 on 2025-06-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_attendance_options_alter_parent_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late',
            field=models.BooleanField(default=False, verbose_name='Опоздал'),
        ),
    ]
