# Generated by Django 5.2.2 on 2025-06-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_attendance_late'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(default=False, verbose_name='Шаблон по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон расписания',
                'verbose_name_plural': 'Шаблоны расписания',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('classroom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Аудитория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('group', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата исключения')),
                ('exception_type', models.CharField(choices=[('cancel', 'Отмена'), ('reschedule', 'Перенос'), ('substitute', 'Замена преподавателя')], max_length=20, verbose_name='Тип исключения')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('new_date', models.DateField(blank=True, null=True, verbose_name='Новая дата')),
                ('new_time', models.TimeField(blank=True, null=True, verbose_name='Новое время')),
                ('new_classroom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Новая аудитория')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.schedule', verbose_name='Расписание')),
                ('substitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_schedules', to='school_app.teacher', verbose_name='Замещающий преподаватель')),
            ],
            options={
                'verbose_name': 'Исключение в расписании',
                'verbose_name_plural': 'Исключения в расписании',
                'unique_together': {('schedule', 'date')},
            },
        ),
    ]
