# Generated by Django 5.2.2 on 2025-06-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_scheduletemplate_schedule_scheduleexception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date', 'start_time'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Аудитория'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Урок отменен'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Расписание, из которого был создан этот урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.schedule', verbose_name='Связанное расписание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'date', 'group', 'start_time')},
        ),
    ]
