# Generated by Django 5.2.2 on 2025-06-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_alter_lesson_options_alter_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleexception',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scheduleexception',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='scheduleexception',
            name='substitute_teacher',
        ),
        migrations.DeleteModel(
            name='ScheduleTemplate',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='ScheduleException',
        ),
    ]
