# Generated by Django 5.1.7 on 2025-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_alter_scheduleexception_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='profile_images/', verbose_name='Изображение пользователя'),
        ),
    ]
