# Generated by Django 5.1.7 on 2025-06-15 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_from_schedule',
            field=models.BooleanField(default=False, verbose_name='Создан из расписания'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки к уроку'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.schedule', verbose_name='Расписание'),
        ),
    ]
